### ISSUE TITLE
How to implement dagger-android when have dynamic feature and regular module togather?

### ISSUE THREAD

**Issue by anggit97** [android/app-bundle-samples#13]
I stuck when try to implement dagger-android when you have dynamic feature module and regular module together. can anyone give me a schema or solution for this problem?

**Comment by keyboardsurfer** [comment]
Please check out https://goo.gle/modular-plaid and https://goo.gle/plaid-dagger for general guidance on Dagger in a modularized application.
I do recommend against using dagger-android in a modularized app as it doesn't work well together.
