### ISSUE TITLE
can not install Language pt/deferredUninstall module in android 8.0

### ISSUE THREAD

**Issue by roths** [android/app-bundle-samples#14]
when i click the "FORCE POLISH" button, the install Activity is open, but can not receive any callback, "deferredUninstall" button is the same

**Comment by keyboardsurfer** [comment]
`deferredUninstall` might happen at any given time in the future, so it's likely you won't immediately receive a callback for this.
The language switch changes must have been fixed by now as I can't reproduce the issue.
