### ISSUE TITLE
Cannot run espresso tests for single class/method

### ISSUE THREAD

**Issue by ThePromoter** [android/app-bundle-samples#18]
Thanks for the update android/android-dynamic-features#32 that includes basic espresso tests for each feature module!  I am able to run them by using the corresponding `:feature:[name]:connectedAndroidTest` gradle task, so our CI concerns are covered.

However, any attempts we've made to setup a run configuration to run a single class, or a single method within a class have been unsuccessful.  Previously, and for unit tests, we're able to right click the class or method and run, but it seems this is not supported with dynamic features.

Trying to run a class within a dynamic feature:
<img width="1084" alt="Screenshot 2019-05-21 17 44 31" src="https://user-images.githubusercontent.com/2645027/58132756-2256eb80-7bf0-11e9-89c3-fac6a15640ef.png">

Trying to run a class within the base application module:
<img width="1086" alt="Screenshot 2019-05-21 17 45 25" src="https://user-images.githubusercontent.com/2645027/58132785-3995d900-7bf0-11e9-8d52-56bb1b001c34.png">

My guess is this is an android studio bug, since running targeted tests works via something like 
```
./gradlew :features:java:connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.google.android.samples.dynamicfeatures.ondemand.JavaSampleActivityTest
```
but if there's a way to get this working I'd love to hear it!  Alternatively, if it is a bug, how should we proceed in reporting it so it can get addressed in a future version?  Thanks!

**Comment by keyboardsurfer** [comment]
This is a [known issue](https://issuetracker.google.com/145191501). Please star it on the Google issuetracker.

**Comment by ivaylo-scaleforce** [comment]
What is the current progress on this issue? Is there a fix already?

**Comment by aumarbello** [comment]
Any update on this?

**Comment by keyboardsurfer** [comment]
This is not a sample issue but one that's [tracked here](https://issuetracker.google.com/145191501) as outlined earlier on this thread. Please check in on that thread for updates.
