### ISSUE TITLE
Dynamic features with Navigation component

### ISSUE THREAD

**Issue by JoaquimLey** [android/app-bundle-samples#20]
I know this might be a little outside of the scope for this sample, but I was wondering if there are any plans to integrate the navigation component in a way to showcase the recommended practices with dynamic features.

I've seen the other `googlesamples` repos and there is no demo available.

I've [asked on SO](https://stackoverflow.com/questions/55532700/navigation-component-with-instant-dynamic-feature-modules) but doesn't seem to be a lot of interest in the community, at least not for now :).

Thanks 🙏 

---------------------
_P.S: Sorry if this shouldn't be an issue but I really didn't find any other place to request where it made sense._

**Comment by keyboardsurfer** [comment]
Once the [Dynamic Feature Navigator](https://developer.android.com/guide/navigation/navigation-dynamic) gets an alpha release, there will be a sample shipped as well.

**Comment by JoaquimLey** [comment]
Thanks for the head's up @keyboardsurfer, I'm going to close this issue now, as it has been answered by Ben and this is the archived repo.
