### ISSUE TITLE
Android App Bundle Buid Error element is missing the 'include' attribute (split: 'kotlin')

### ISSUE THREAD

**Issue by yibinstudio** [android/app-bundle-samples#23]
hi,there is something wrong when i try to upload the app.aab to google play.So i use bundletool to build-apks by the app.abb,the command line print the error message like this,Android App Bundle Buid Error element is missing the 'include' attribute (split: 'kotlin'),but i check the manifest file ,there is a 'include' attribute behind 'fusing', so i am confused.how can i fix this problem

**Comment by keyboardsurfer** [comment]
Closing this as it seems stale. If the issue persists, please comment.
