### ISSUE TITLE
Error while downloading the sample app from the play store

### ISSUE THREAD

**Issue by garg-ketki** [android/app-bundle-samples#32]
I tried to upload the sample app on play store by changing the `applicationId`. But it's not working for me. I am getting an error "Item not found". 

Please find below snapshot for reference:
![device-2019-10-15-111128](https://user-images.githubusercontent.com/22368509/66803210-96e24c00-ef3c-11e9-868a-8f234c657845.png)

**Comment by keyboardsurfer** [comment]
Which channel are you testing this on? Alpha / Beta

**Comment by garg-ketki** [comment]
> Which channel are you testing this on? Alpha / Beta

I am using the Alpha channel for testing.

**Comment by keyboardsurfer** [comment]
I can not reproduce the issue. A common issue is that the email address is not added to the testers list. Follow the [instructions](https://support.google.com/googleplay/android-developer/answer/3131213#closed_beta) to enable it.
