### ISSUE TITLE
Instrumentation tests can't find install-time feature modules.

### ISSUE THREAD

**Issue by jaysondc** [android/app-bundle-samples#35]
I'm trying to set up some basic espresso tests in my app that uses dynamic feature modules. Both my feature modules are install-time and they show up and are able to be accessed via reflection when i run my app on device/on emulator. But as soon as I try to run in either a unit test or instrumentation test, SplitInstallManager shows there are no modules installed!

Am I missing something with regards to how dynamic features are treated during tests?

The command I'm using is 
`./gradlew connectedAndroidTest --no-parallel`

**Comment by keyboardsurfer** [comment]
Thanks. Fixed within 78a1150f03f5f4916880ae07478d8c25fdaac607
