### ISSUE TITLE
[Dynamic feature] Crash when navigate back to fragment

### ISSUE THREAD

**Issue by georgious1** [android/app-bundle-samples#39]
I am using fragment in dynamic feature module. 
In fragment have these lines of code:
`  override fun onAttach(context: Context?) {
        super.onAttach(context)
        SplitCompat.install(context) }`

Everything works fine. But when i am trying to navigate back to this fragment i am getting ResourceNotFoundException. It looks like my dynamic module wasnt even initialized.

Issue was solved using next lines 
`override fun onResume() {
        super.onResume()
        SplitCompat.install(context)
    }`

What is the proper way to fix it ?

**Comment by keyboardsurfer** [comment]
Thanks for reporting this. It seems like this is not an issue with the sample itself but one you're encountering in your own application.

Can you please give me some more information on your Activity / Fragment / Module setup & stacktrace over at [StackOverflow](https://stackoverflow.com/questions/ask) and link it here?

**Comment by keyboardsurfer** [comment]
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.

**Comment by Rishabh-sx** [comment]
Hi @keyboardsurfer @georgious1 , I am also facing this when navigating back to fragment.

I have added this in activity.
 override fun onResume() { super.onResume() SplitCompat.install(context) }

But I am getting crash in API response.

**Comment by Rishabh-sx** [comment]
Any Standard way to fix this ?

**Comment by keyboardsurfer** [comment]
Is there a way for you to reproduce the issue within this sample or a clone of it?

**Comment by Rishabh-sx** [comment]
Hi @keyboardsurfer, Not in this sample but in our application we are facing this after following all the steps to turn on Dynamic Delivery.

**Comment by keyboardsurfer** [comment]
I understand this. What I'm asking you is to try and reproduce the issue on the sample at hand. If it's reproducible here we can take a closer look.

**Comment by Rishabh-sx** [comment]
No, I was not able to reproduce it in this sample. I am just looking for help which I am not getting in Community right now. Can you help me and my team in tackling this issue as we have 100,000,000+ users and we are dealing with crashes and planning to turn off Dynamic Delivery and look forward for a solid way

**Comment by Rishabh-sx** [comment]
Okay, let me check and get back to you.

**Comment by georgious1** [comment]
@Rishabh-sx  i added workaround to fix this issue. 
 enable SplitCompat to have immediate access for code and resources
https://developer.android.com/guide/playcore/dynamic-delivery#activity_splitcompat

 Android docs says : 
["As long as you enable SplitCompat for your base application context and the activities in your dynamic feature module, after a request for an on demand module reports as INSTALLED, you can start using its code and resources as if it were a part of the base APK..." ](https://developer.android.com/guide/playcore/dynamic-delivery#activity_splitcompat)

BUT

1) I enabled SplitCompat in my Application class, and my dynamic feature modules didnt have any activities, only fragments. But for sure i added following code to my activity(which was not part of DFModule).

```
override fun attachBaseContext(baseContext: Context) {
        super.attachBaseContext(baseContext)
        SplitCompat.installActivity(baseContext)
    }
```

AND
2) When receive `SplitInstallSessionStatus.INSTALLED` status i immediately called
` SplitCompat.install(context.applicationContext)` with application context. And only after i call any code from DFModule


3) Added following to Fragment from DFModule

```
override fun onAttach(context: Context?) {
        super.onAttach(context)
        SplitCompat.install(context)

```

Actually i think just number (2) is did all the trick, and enabling SplitCompat in fragments looks like redundant, but wont create any issues.

**Comment by georgious1** [comment]
Ah, and small update here, rechecked docs. Maybe its new addition, but it describes step (2) from example above : 
".. If you want to access assets or resources that exist in the newly installed module from a different installed module of your app, you must do so using the application context. The context of the component that's trying to access the resources will not yet be updated. Alternatively, you can recreate that component **or install SplitCompat upon it after the dynamic feature module install.** "

**Comment by Rishabh-sx** [comment]
Hi @georgious1 , Thanks for sharing this information. Let me share this with my team and ask them to check if we are missing something.
