### ISSUE TITLE
Missing Test and AndroidTest default folders in Dynamic Feature Module?

### ISSUE THREAD

**Issue by rajBopche** [android/app-bundle-samples#49]
I added a new dynamic feature module to my android project. When the new module was created, the 
"src/test" and "src/androidTest" folders were missing. I was expecting them to be present by default. How can I write test cases in a dynamic feature module? Am I missing something?

**Comment by keyboardsurfer** [comment]
You can create the tests the same way as in an application module. Can you give me some more info on how you created the module and which Android Studio version you used?

**Comment by rajBopche** [comment]
Android Studio Specs: 
<img width="639" alt="Screenshot 2020-03-20 at 6 11 06 AM" src="https://user-images.githubusercontent.com/42612104/77127259-d8d66780-6a71-11ea-9ec5-e54c728907b0.png">

Steps For Dynamic Module Creation: **File -> New -> New Module -> Dynamic Feature Module**

**Comment by keyboardsurfer** [comment]
I just tested on 4.1 canary. But it should already be fixed in 4.0.
