### ISSUE TITLE
SplitInstallInfoProvider : No metadata found in AndroidManifest

### ISSUE THREAD

**Issue by ankit4code** [android/app-bundle-samples#52]
While creating dynamic on demand module, I'm getting this error when SplitInstallManager starts downloading this module
`I/PlayCore: UID: [10488]  PID: [31266] SplitInstallInfoProvider : No metadata found in AndroidManifest.
I/PlayCore: UID: [10488]  PID: [31266] SplitInstallService : startInstall([AadharModule],[])
I/PlayCore: UID: [10488]  PID: [31266] SplitInstallService : Initiate binding to the service.
I/PlayCore: UID: [10488]  PID: [31266] SplitInstallService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.splitinstallservice.SplitInstallService})
I/PlayCore: UID: [10488]  PID: [31266] SplitInstallService : linkToDeath
I/PlayCore: UID: [10488]  PID: [31266] SplitInstallService : Unbind from service.
I/PlayCore: UID: [10488]  PID: [31266] SplitInstallService : onError(-5)`

**Comment by keyboardsurfer** [comment]
Can you please let me know if this is an issue with one of the samples in this repository.
Otherwise please post to StackOverflow with a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) and link here, so we can follow up.

**Comment by ankit4code** [comment]
Thanks @keyboardsurfer
No issue with these samples, I got error in mine project and that too solved after some code refactoring. I'm closing this.

**Comment by viveksamele08** [comment]
Hello , 
@ankit4code  I am also facing this issue any hint how did you fixed this, I am stuck here for a long time,

**Comment by ankit4code** [comment]
@viveksamele08 In my case, the error was with the String I was assigning to my module. Actually when I saw the error I realized It was searching the module with wrong module name.

This was the error
I/PlayCore: UID: [10488] PID: [31266] SplitInstallInfoProvider : No metadata found in AndroidManifest. I/PlayCore: UID: [10488] PID: [31266] SplitInstallService : startInstall([**AadharModule**],[])

Here you can see I've given title to my module with **@string/title_aadhar_module**

`<dist:module
      dist:instant="false"
        dist:title="@string/title_aadhar_module">
        <dist:delivery>
            <dist:on-demand />
        </dist:delivery>
        <dist:fusing dist:include="true" />
    </dist:module>`





For me the only solution was to give right string value for my module
Since my module name was aadhar_module, I gave the same name to string 

`<string name="title_aadhar_module">aadhar_module</string>`

And it seriously worked for me.

Hope it'll help you.
Thanks

**Comment by keyboardsurfer** [comment]
@ankit4code which module is the `@string/title_aadhar_module` in?

**Comment by viveksamele08** [comment]
> @keyboardsurfer  this is in base app or main module bye default, and it is your wish where you want to keep .

**Comment by viveksamele08** [comment]
> @viveksamele08 In my case, the error was with the String I was assigning to my module. Actually when I saw the error I realized It was searching the module with wrong module name.
> 
> This was the error
> `I/PlayCore: UID: [10488] PID: [31266] SplitInstallInfoProvider : No metadata found in AndroidManifest. I/PlayCore: UID: [10488] PID: [31266] SplitInstallService : startInstall([**AadharModule**],[])`
> 
> Here you can see I've given title to my module with **@string/title_aadhar_module**
> 
> ```
> <dist:module
>     dist:instant="false"
>     dist:title="@string/title_aadhar_module">
>     <dist:delivery>
>         <dist:on-demand />
>     </dist:delivery>
>     <dist:fusing dist:include="true" />
> </dist:module>
> ```
> 
> For me the only solution was to give right string value for my module
> Since my module name was aadhar_module, I gave the same name to string
> 
> `<string name="title_aadhar_module">aadhar_module</string>`
> 
> And it seriously worked for me.
> 
> Hope it'll help you.
> Thanks

Thanks Ankit It helped my i had issue with this as well one issue about the pakage name, It works for me..

**Comment by keyboardsurfer** [comment]
Yes, it needs to be in the base module. Also out of curiosity, did your module name have any spaces or dashes in there before you changed it?

**Comment by viveksamele08** [comment]
> Yes, it needs to be in the base module. Also out of curiosity, did your module name have any spaces or dashes in there before you changed it?

No i doesn't have any spaces, there was just wrong package name in graph not in manifest . 

One more important thing here GRaph name must have the correct module name. though in manifest it doesn't verify it is just a titile not the module name.
