### ISSUE TITLE
Dynamic feature module resource not found on some devices

### ISSUE THREAD

**Issue by bashtian** [android/app-bundle-samples#63]
I have a dynamic feature module that has drawable resources that I want to use inside the dynamic feature module. It works, but there are crash reports from some devices indicating that the drawable from the dynamic module can not be found:

```
android.content.res.Resources$NotFoundException: 
  at android.content.res.ResourcesImpl.getValueForDensity (ResourcesImpl.java:285)
  at android.content.res.Resources.getDrawableForDensity (Resources.java:964)
  at android.content.res.Resources.getDrawable (Resources.java:880)
  at android.content.Context.getDrawable (Context.java:689)
  ...
```
I don't have a way to reproduce it yet. I am using the DynamicNavHostFragment for loading the module. 

Any idea what could be the problem or is there a way to debug this, maybe listing all apks installed for the app with the included resources?

edit: The drawables are used programmatically with ```Context.getDrawable()```, did not try to use them in a layout yet.

**Comment by bashtian** [comment]
I was able to reproduce it now.

When loading the module for the first time it works correctly, but when the app is restarted the resources are not found anymore for this module.

There is an error when the app is restarted and the module is loaded again:

	No package ID 7d found for ID 0x7d020000

**Comment by keyboardsurfer** [comment]
It seems like you're describing an issue that is not directly related to the sample.
We are tracking a [similar issue](https://issuetracker.google.com/160441972) already. Please add any information that can be useful to reproduce the issue there.

**Comment by keyboardsurfer** [comment]
Duplicating this issue into #36 for the time being.
