### ISSUE TITLE
Not wotking assembleRelease on DynamicFeatures

### ISSUE THREAD

**Issue by tprochazka** [android/app-bundle-samples#64]
I found one very weird error, I spent several hours on it and I don't understand if it is just a lint error or something in the project.

I tried to build demo DynamicFeatures with `assembleRelease`, it just needs to add this to app/build.gradle

```
    signingConfigs {
        release {
            storeFile ...
            keyAlias ...
            storePassword ...
            keyPassword ...
        }
    }

```
and run `assembleRelease` and it always fail with

```
> Task :features:java:lintVitalRelease
C:\PJazyky\_Experiments\app-bundle-samples-master\DynamicFeatures\features\java\src\main\AndroidManifest.xml:31: Error: JavaSampleActivity must extend android.app.Activity [Instantiatable]
        <activity android:name="com.google.android.samples.dynamicfeatures.ondemand.JavaSampleActivity">
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "Instantiatable":
   Activities, services, broadcast receivers etc. registered in the manifest
   file (or for custom views, in a layout file) must be "instantiatable" by
   the system, which means that the class must be public, it must have an
   empty public constructor, and if it's an inner class, it must be a static
   inner class.

1 errors, 0 warnings

```

I'm sure that all activities extend `android.app.Activity`.
And its event works correctly for `assembleDebug`.
I also tried to change minifyEnabled to false on release build and it still happens.
Should I report it as lint check error or I miss something?

**Comment by keyboardsurfer** [comment]
The sample relies on using app bundles. As such, use `bundleRelease` instead of `assembleRelease`.
