### ISSUE TITLE
Dynamic feature Update size is more the install Size

### ISSUE THREAD

**Issue by amitgroch** [android/app-bundle-samples#68]
I have upload bundle with Dynamic feature, We are facing a size issue when we are going to update the app from the play store it shows more size but if we will go install apk from play store it shows less size from the update size.

**Comment by keyboardsurfer** [comment]
Before we go any further, this is not an issue with the samples at hand.  
Usually updates use delta downloads through the Play Store.
When switching from apk to app bundles your users currently will have to download the entire app in an update process.
This is a one off and once your app is distributed as app bundle, users will be able to benefit from delta downloads again.

**Comment by amitgroch** [comment]
Hi sir,
Thanks for your reply

Actually our app on play store already in the bundle mode and when we are going update that bundle(apk) from play store it shows large size for example If I am going first time install the app from play store it shows 11MB file size and when I am going update that bundle(apk) from play store it show 22MB file size.

**Comment by amitgroch** [comment]
Hi sir,
Thanks for your reply

Actually our app on play store already in the bundle mode and when we are going update that bundle(apk) from play store it shows large size for example If I am going first time install the app from play store it shows 11MB file size and when I am going update that bundle(apk) from play store it show 22MB file size.

**Comment by keyboardsurfer** [comment]
This doesn't seem to be an issue
It seems like you're describing an issue that is not directly related to the sample.
Please use [StackOverflow](stackoverflow.com) for issues related to your modified implementation.
