### ISSUE TITLE
 Incorrect error code on "insufficient free space"

### ISSUE THREAD

**Issue by abeyn** [android/app-bundle-samples#7]
Steps:
1. Start download feature module
2. Receive: SplitInstallErrorCode.INTERNAL_ERROR (-100)
3. Open logcat:
08-16 13:17:29.389 E/Finsky  (20334): [1] los.e(15): Cancel download of com.absolutist.hiddennumbers because insufficient free space (isid: LCwZoutOTlCETB8_M0jhrQ)
So, incorrect error.
Expeced error code: SplitInstallErrorCode.INSUFFICIENT_STORAGE

**Comment by keyboardsurfer** [comment]
Thank you for reporting this.
Can you please verify which version of the PlayCore sdk you used when the error occurred?

**Comment by keyboardsurfer** [comment]
Can you verify that this issue persists with a recent version of the Google Play Store in combination with the latest PlayCore version?

**Comment by yaboililc11** [comment]
How would I be able to?

**Comment by keyboardsurfer** [comment]
The issue should have been fixed in recent releases.
