### ISSUE TITLE
How do you show the review dialog via the sample?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/app-bundle-samples#72]
I saw that PlayCoreKtx is supposed to demonstrate it, but all I see when I run it, is a weird flashlight app...
https://github.com/android/app-bundle-samples

How come?
I want to have a button on the settings screen that the user can always reach manually, to put a review. Even if he already did, it can be that he changed his mind.
So that's why I want to try out this sample.

**Comment by skimarxall** [comment]
Hi,

See the In-app review testing section https://developer.android.com/guide/playcore/in-app-review/test

**The app must be in Google Play for the review to work.** 

_"I want to have a button on the settings screen that the user can always reach manually"_
This goes against the design guidelines and it's not a supported use case for now
https://developer.android.com/guide/playcore/in-app-review#when-to-request

**Comment by AndroidDeveloperLB** [comment]
I see. So I need to change the package name of the app to some app that does exist on the Play Store?
I tried this code on my app that's already published, and it doesn't seem to do anything even though it has a callback to addOnCompleteListener:

```
val manager = ReviewManagerFactory.create(activity!!)
val request = manager.requestReviewFlow()
request.addOnCompleteListener { request ->
    if (request.isSuccessful) {
        Log.d("AppLog", "request.isSuccessful")
        val reviewInfo = request.result
        val flow = manager.launchReviewFlow(activity!!, reviewInfo)
        flow.addOnCompleteListener { _ ->
            Log.d("AppLog", "addOnCompleteListener")
        }
    } else {
        Log.d("AppLog", "err")
    }
}
```

As for the button, seems you are right.

Seems very pointless to use this SDK then, because it isn't reliable at all and it's very restricted :

> The flow has finished. The API does not indicate whether the user reviewed or not, or even whether the review dialog was shown. Thus, no matter the result, we continue our app flow.

> calling a launchReviewFlow method might not always display a dialog. For example, you should not have a call-to-action option (such as a button) to trigger a review as a user might have already hit their quota and the flow won’t be shown, presenting a broken experience to the user.

So I have 2 possible scenarios and both don't seem to fit:

1. I was hoping that I could have my button that goes to the Play Store to put a review (the user has full control of when to do it, on his own) - to use this API, but I can't even check if it can show a UI.
2. After a long time of using the app, a dialog could appear to tell the user that maybe he would like to rate the app. If this API can't promise me anything to be shown, and I tell the user to click "next" or something to reach the review screen, it can still fail, according to the docs, and there is nothing I can do about it and I can't even know that it failed...

So I don't get it:
When would such a thing be useful, at all?
Why would Google offer such an unreliable API? 
Why can't we have the best UX for this?
It's much better to avoid annoying users about this, to let users to reach it by themselves...
Why not provide an API that I can at least know that I can use? So that I won't show something before, and then get nothing working?

**Comment by keyboardsurfer** [comment]
> After a long time of using the app, a dialog could appear to tell the user that maybe he would like to rate the app. If this API can't promise me anything to be shown, and I tell the user to click "next" or something to reach the review screen, it can still fail, according to the docs, and there is nothing I can do about it and I can't even know that it failed...

You can achieve this most of this scenario using the given API.
1. You persist your criteria for rating the API
2. Check whether the criteria has been met
3. Call `launchReviewFlow` or  `launchReview` once the the criteria is met
4. Implement an `OnCompleteListener` and continue the app's flow regardless of result

You won't need any UI affordance to on your end but can rely on Google Play to let you know that your app is in control again through the `OnCompleteListener`.

**Comment by AndroidDeveloperLB** [comment]
@keyboardsurfer So as I wrote, it's unreliable and I can't show a dialog before, as opposed to what the docs say:

> Do not prompt the user excessively for a review. This approach helps minimize user frustration and limit API usage (see the section on quotas).
> Your app should not ask the user any questions before or while presenting the rating button or card, including questions about their opinion (such as “Do you like the app?”) or predictive questions (such as “Would you rate this app 5 stars”).

That's as opposed to what you write now, that I shouldn't show anything at all before.
Why should I show the reviewing UI of the library without any introduction? Without any context before? 
It makes no sense for the user. 
Very bad UX, to show some reviewing out of nothing.
Could be seen as a bad attempt to work like an ad, to increase rating, or a bug as it shows it without any context and any request from the user to show it.
Not only that, but by doing it, you don't give me the choice of letting the user choose how to support the app.
On my app, for example I don't ask for a review. I give the user multiple choices: "review", "share", "donate", and of course, "maybe later".

Your solution makes no sense.

**Comment by keyboardsurfer** [comment]
This is a discussion out of scope of this sample or the issues surrounding it. Bringing it to a conclusion with the currently highlighted points.

The API is technically reliable and documented through the [documented flow](https://developer.android.com/guide/playcore/in-app-review/kotlin-java?hl=en#kotlin) which can be simplified like this:

1. Call API, implement `OnCompleteListener` and attach it
2. Resume your usual app's flow once `onComplete` is called

There are best practices and guidelines quoted by you are available in [the documentation](https://developer.android.com/guide/playcore/in-app-review?hl=en#when-to-request) as well.

The use case you are outlining, which requires active user interaction, is not covered by the API at this point.

**Comment by AndroidDeveloperLB** [comment]
Actually no. Sadly the sample still doesn't work. I tried to update the dependency. All it does is a flashlight app.
Why spend so much effort into a flashlight app instead of showing how to use the API and that's it?
How can you say it's fixed exactly, and close it?
How can the API be considered reliable, if the sample that's supposed to use it fails in doing so?
Please show how to test it out, on both the sample and on real apps.

Even on a real app ( my app), it fails to show.

And all I did is this:

```kt
val manager = ReviewManagerFactory.create(activity!!)
val request = manager.requestReviewFlow()
request.addOnCompleteListener { request ->
    if (request.isSuccessful) {
        Log.d("AppLog", "request.isSuccessful")
        val reviewInfo = request.result
        val flow = manager.launchReviewFlow(activity!!, reviewInfo)
        flow.addOnCompleteListener { _ ->
            Log.d("AppLog", "addOnCompleteListener")
        }
    } else {
        Log.d("AppLog", "err")
    }
}
```

So tell me, why should it fail? How can I test it to see that it works? When can I use it, with proper introduction before?
The links you've provided don't answer any of these. They actually say this is how it's done. 
This is the code I'm supposed to use.
I can see the logs reaching "addOnCompleteListener" being printed, but nothing is shown. Not even on the first time I get it.
To me it seems like a completely unreliable thing to use. Says it's ready to show, but never shows.
