### ISSUE TITLE
All modules with native libraries must support the same set of ABI but module 'base' supports '[ARM64_V8A, ARMEABI_V7A, X86, X86_64]' and module 'trace_module' supports '[ARM64_V8A, ARMEABI_V7A, ARMEABI, MIPS, MIPS64, X86, X86_64]'.

### ISSUE THREAD

**Issue by bjprogrammer** [android/app-bundle-samples#8]
I am not able to generate .aab build. I am getting this error-
All modules with native libraries must support the same set of ABIs, but module 'base' supports '[ARM64_V8A, ARMEABI_V7A, X86, X86_64]' and module 'trace_module' supports '[ARM64_V8A, ARMEABI_V7A, ARMEABI, MIPS, MIPS64, X86, X86_64]'.

**Comment by omarfuzzer** [comment]
Help!!!! the same thing happens to me, how can I solve it?

**Comment by bjprogrammer** [comment]
This happened randomly for me. Most probably when some of your modules or third party library support only some of the architectures. 
Easiest way would be to disable  abi split at app level gradle-
 bundle {
        language {
            enableSplit = true
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = false
        }
    }
But this will increase you app download size and android app bundle will be useless to a greater extent.

Other way would be to restrict your dynamic module to only certain architectures in order to have sam set of ABIs-
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 12
        versionName "1.2"
  ndk{
            abiFilters "ARM64_V8A", "ARMEABI_V7A", "X86", "X86_64"
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"

        }
This would reduce your app support to only selected architectures

I would suggest try invalidating cache and restart android studio as this error happens randomly and sometimes when app build is not properly. For me this worked when I used one of the above methods and then removed them later on.

**Comment by keyboardsurfer** [comment]
I'm unable to verify this behavior in any of the samples within the repository.

**Comment by keyboardsurfer** [comment]
As this seems to be a question on your own app rather than on this sample I defer to [asking it on StackOverflow](https://stackoverflow.com/questions/ask) instead.
