### ISSUE TITLE
In-App Review Prompt - Explain meaning of 1 star and 5 stars

### ISSUE THREAD

**Issue by InternetMaster1** [android/app-bundle-samples#88]
Thanks for the amazing In-App Reviews feature.

I had a small suggestion - Many a times, the users are confused whether a 1 star is the best rating or a 5 star is the best rating.

We have received so many 1 star ratings with raving reviews for our app.

The Play Store website has full clarity when giving reviews. It prints what a rating means.
1 Star - Hated It
2 Stars - Didn't Like It
3 Stars - Just OK
4 Stars - Liked It
5 Stars - Loved It

![image](https://user-images.githubusercontent.com/16253584/95291806-e6c4cc00-088d-11eb-8d98-2246d8e033ec.png)

![image](https://user-images.githubusercontent.com/16253584/95291850-fba15f80-088d-11eb-8453-e8bfa1bedfed.png)

Can we have similar wordings for the In-App Review Prompt? Currently it doesn't have any such indicators.
![image](https://user-images.githubusercontent.com/16253584/95291971-360afc80-088e-11eb-8901-7f6e2498caf7.png)

**Comment by InternetMaster1** [comment]
@keyboardsurfer @wojtek-kalicinski

**Comment by keyboardsurfer** [comment]
Hi and thanks for asking this question. As it's not directly related to this sample but the underlying library, we can't make any change on this repository to help you with this.

I recommend to file an issue at the [Google IssueTracker](https://issuetracker.google.com/issues/new?component=384531), where it can be routed into the right direction more easily. Once you have filed the issue there, please let me know here, so we can follow up on it.

**Comment by InternetMaster1** [comment]
@keyboardsurfer 

I have added an issue in the Google Issue Tracker. Thank you so much for offering to follow up on the same
https://issuetracker.google.com/issues/170373343

**Comment by InternetMaster1** [comment]
Dear @keyboardsurfer 

It has been almost 6 months that I submitted this bug to Google Issue Tracker. It got "assigned" and marked as a P2 bug.

But the solution has still not been launched.

Our app rating fell down from 4.4 to to 3.8 over a course of few months due to too many misunderstood 1 stars.

If this isn't actively being worked upon, should we revert back to our older review system & remove the In-app review implementation?

Please guide us! Thanks

**Comment by whatyouwannado** [comment]
how do I stop or can n e one please change any changes I may have done

Bobbi Bowker (sent from mobile)

**Comment by keyboardsurfer** [comment]
With this being tracked on the issuetracker, I recommend continuing the discussion there.
The issue has been prioritised by the team and will be addressed eventually, but a timeline is not available at the moment.
