### ISSUE TITLE
Network error doesn't triggered in downloading session

### ISSUE THREAD

**Issue by abeyn** [android/app-bundle-samples#9]
Steps:
1. Put large file in assets folder;
2. Build and upload to store;
3. Install and run application;
4. Start load dynamic feature "assets";
5. Disable WiFi
6. No errors or new states, application hangs...

Expected behavior:  SplitInstallErrorCode.NETWORK_ERROR

**Comment by keyboardsurfer** [comment]
Thanks for reporting this.
Can you be more specific on "application hangs"? Does this mean you see an ANR?
If possible can you also include a stacktrace?

**Comment by keyboardsurfer** [comment]
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.
